command /forcefreeall:
    permission: op
    trigger:
        # Rensa arenastatus
        loop {arena::list::*}:
            set {arena::%loop-value%::occupied} to false
        
        # Rensa alla köer
        delete {queue::*}
        loop all players:
            delete {queuing::%loop-player%}
            delete {queuekit::%loop-player%}
            
        send "{@prefix} &c&lALLA arenor är nu tvingade till 'FREE' och alla köer är rensade!" to player
